server:
  port: 8022

spring:
  application:
    name: rabbitmq-consumer
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: '{cipher}116855e7e33c5f0a928140785058690c934aa780b71ae3b024929182239729e4'
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/daifylearn/cloud-config
          search-paths: /config,/base-config-client,/base-config-client-encryption
#        encrypt:
#          enabled: true
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15

