server:
  port: 7889
spring:
  application:
    name: consumer_1
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
          zk-nodes: localhost:2181
          auto-create-topics: true
      bindings:
        #input是接收，注意这里不能再像前面一样写output了
        myInput:
          destination: stream-demo
          group: group
        #myOutput:
          #destination: stream-demo-trans
          consumer:
            partitioned: true   #开启分区
      instance-count: 2 #消费者总数
      instance-index: 0 #当前消费者的索引
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15