server:
  port: 7888

spring:
  application:
    name: producer
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092         #Kafka的消息中间件服务器
          zk-nodes: localhost:2181        #Zookeeper的节点，如果集群，后面加,号分隔
          auto-create-topics: true        #如果设置为false,就不会自动创建Topic 有可能你Topic还没创建就直接调用了。这个不用自动创建Topic的应该就可以不用配置了我猜测的
          autoAddPartitions: true
      bindings:
        myOutput:      #自定义的myOutput
          destination: stream-demo    #消息发往的目的地
          #content-type: text/plain    #消息发送的格式，接收端不用指定格式，但是发送端要，不指定好像也没事
          producer:
            partitionKeyExpression: headers['partitionKey']   #分区的关键字，对象中的id，对象
            partitionCount: 2    #Key和分区数量进行取模去分配消息，这里分区数量配置为2
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15